// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nvxkcepdvpyqjxbrthgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52eGtjZXBkdnB5cWp4YnJ0aGdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MDAyOTUsImV4cCI6MjA3MDM3NjI5NX0.9RT90xiXfIp0rWSkTa942ajdui7EZcTF070D2YxUo2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);